# Generated by Django 5.1 on 2025-12-23 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('forwarding', 'Forwarding'), ('ended', 'Ended'), ('busy', 'Busy'), ('no-answer', 'No Answer'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('duration', models.IntegerField(default=0, help_text='Call duration in seconds')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('assistant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call History',
                'verbose_name_plural': 'Call Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('failed_calls', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Calling Session',
                'verbose_name_plural': 'Calling Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
