# Generated by Django 4.2.9 on 2025-12-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_knowledgedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('columns', models.JSONField()),
                ('vapi_tool_ids', models.JSONField(default=list)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
