# Generated by Django 4.2.9 on 2025-12-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_connecteddatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='connecteddatabase',
            name='connection_details',
            field=models.JSONField(default=dict),
        ),
    ]
