# Generated by Django 5.1 on 2025-12-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_connecteddatabase_connection_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='callingsession',
            name='assistant_id',
            field=models.CharField(blank=True, help_text='Vapi Assistant ID for inbound calls', max_length=255, null=True),
        ),
    ]
