# Generated by Django 5.1 on 2025-12-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_assistant_id_to_calling_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingsession',
            name='assistant_id',
            field=models.CharField(blank=True, help_text='Vapi assistant ID for inbound calls', max_length=255, null=True),
        ),
    ]
