# Generated by Django 5.1 on 2025-12-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_callingsession_assistant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('expert_field', models.CharField(max_length=255)),
                ('vapi_tool_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Human Expert',
                'verbose_name_plural': 'Human Experts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='callingsession',
            name='assistant_id',
        ),
    ]
