# Generated by Django 5.1 on 2025-12-29 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_humanexpert_remove_callingsession_assistant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanexpert',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='humanexpert',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='humanexpert',
            name='vapi_tool_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
