# Stage 1: Build React
# STAGE 1: Install & Build
FROM node:20-slim AS builder
WORKDIR /app
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
COPY package*.json ./
RUN npm install
COPY . .
# This creates the .next folder inside the container
RUN npm run build

# STAGE 2: Production Run
FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production

# We copy only what we need from the builder stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

# Now npm IS available because the base is node:18-slim
CMD ["npm", "start"]